matrix:
  include:
    - language: elixir
      elixir: 1.5.1
      services:
        - postgresql
      addons:
        postgresql: "9.6"
      before_script:
        - mix deps.get
        - cd apps/plustwo
        - MIX_ENV=test mix event_store.create
        - cd ../..
      script:
        - mix test
        - mix credo --strict
